### ISSUE TITLE
Windows 10: Display scale not respected (I suspect)

### ISSUE THREAD

**Issue by rejhgadellaa** [BoffinbraiN/windows-guification-themes#3]
I'm having a hard time making a screenshot of it but I think that the notifications are having trouble with display scaling. I use pidgin on a macbook pro retina with windows and the second line goes through the protocol icon and the avatar is not shown at all

I don't remember seeing this on my desktop (display scale 100%)

**Comment by BoffinBrain** [comment]
My themes use absolute positioning rather than percentages, so it's possible that UI scaling breaks it. However, I'd also expect to see other themes breaking in the same way. Can you verify it with the other default themes?

For display pictures, I believe Guifications falls back on using the protocol icon for some protocols if it cannot find an avatar. In addition to that, the relevant protocol must have icons installed for the appropriate sizes (16x16 for the small ones, or 48x48 if substituting for the avatar). Which protocol(s) are you using and do the icons show correctly on other default themes?

**Comment by rejhgadellaa** [comment]
Sry for the late reply. I'll have to give it a try but i need the notification to trigger :P

I'm using pidgin for xmpp/jabber only so i'm not sure if this is the only one with the problem.

**Comment by BoffinBrain** [comment]
OK, I'll wait until you can produce screenshots. I don't have access to a MacBook so you'll have to be the guinea pig! There's a good chance I won't be able to do anything if the bug lies in Guifications' lack of high-DPI support.

You might want to add a second protocol or account to Pidgin so you can friend yourself and trigger test notifications. If you have a Steam account, for instance, you can download a plugin for that and get plenty of friend activity that way.

**Comment by BoffinBrain** [comment]
Closing this issue since it's probably a Guifications bug.
